# Numpy
Numerisk python
- Array (fält)
- Lik listor
- Matematiska operationer på arrays
- Modellera vektorer och matriser




In [6]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1[0])
print(array1[-1])
print(array1[1:4]) #slicing

lista = [1,2,3,4]

print(lista*2)
print(array1+2)




1
9
[2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 3  4  5  6  7  8  9 10 11]


In [8]:
import numpy as np

x = np.arange(1, 10)
print(x)

# y = kx + m

def f(k, x, m):
    y = k*x + m
    return y
# y = 2x + 2

print(f(2, x, 2))

[1 2 3 4 5 6 7 8 9]
[ 4  6  8 10 12 14 16 18 20]
